
# START_INDEX = 6
# END_INDEX = 12
# PATTERN_CHAR = '*'
# LOG_PATH = 'CMS/STATEMENTLOG/'
# FEE_TYPE_CASH_ADVANCE_FEE = 'FEC007'
# CARD_CATEGORY_MAIN = 'M'
# CARD_CATEGORY_CO_BRANDED = 'CO'
# CARD_CATEGORY_AFFINITY = 'A'
# CARD_CATEGORY_ESTABLISHMENT = 'E'
# CARD_CATEGORY_FD = 'F'
# CASH_ADVANCE_FEE = 'FEC007'
# STATEMENT_FILE_PATH = 'CMS/EOD/STATE/'

START_INDEX = 6
END_INDEX = 12
PATTERN_CHAR = '*'
EODDATE = ''
LOG_PATH = 'C:\\CMS\\STATEMENTLOG\\'
FEE_TYPE_CASH_ADVANCE_FEE = 'FEC007'
CARD_CATEGORY_MAIN = 'M'
CARD_CATEGORY_CO_BRANDED = 'CO'
CARD_CATEGORY_AFFINITY = 'A'
CARD_CATEGORY_ESTABLISHMENT = 'E'
CARD_CATEGORY_FD = 'F'
CASH_ADVANCE_FEE = 'FEC007'
STATEMENT_FILE_PATH = 'C:\\CMS\\STATE\\'
